[package]
versioned_files = ["package.json"]
changelog = "CHANGELOG.md"
assets = "gel-better-auth.tgz"

[github]
owner = "carere"
repo = "gel-better-auth"

[[workflows]]
name = "pre-release"
help_text = "Create a pre-release for the project"

[[workflows.steps]]
type = "Command"
command = "git checkout -b knope/pre-release"

[[workflows.steps]]
type = "PrepareRelease"

[[workflows.steps]]
type = "Command"
command = "bun biome check --write ."

[[workflows.steps]]
type = "Command"
command = "git add ."

[[workflows.steps]]
type = "Command"
command = "git commit -m \"chore: prepare release $version\""

[[workflows.steps]]
type = "Command"
command = "git push origin -u knope/pre-release"

[[workflows.steps]]
type = "Command"
command = "gh pr create -b main -t \"chore: release $version\" -b \"Changes shipped with the release:\n\n$changelog\""

[[workflows.steps]]
type = "Command"
command = "gh release create $version --draft --title \"$version\" --note \"$changelog\""
