name: Pre-Release

on:
  workflow_dispatch:

jobs:
  pre-release:
    if: github.event_name == 'workflow_dispatch' && github.ref == 'main'
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Knope
        uses: knope-dev/action@v2.1.0
        with:
          version: 0.21.0

      - name: Install dependencies
        run: bun ci

      - name: Run Knope Pre-Release
        run: knope pre-release
